#!/bin/bash
# source ~/code/myLinux/cmd/kuti
# dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ## old
dir=`dirname $0`
alias ll="ls -lh"
alias a="atom ."
alias storm="/usr/local/bin/wstorm ."
alias intel="/Applications/IntelliJ\ IDEA\ 14\ CE.app/Contents/MacOS/idea ."
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ."
source $dir/kuti
