#!/bin/bash
# source ~/code/myLinux/cmd/kuti
# dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ## old
dir=`dirname $0`
alias ll="ls -lh"
alias a="atom ."
alias w="/usr/local/bin/wstorm ."
alias i="/Applications/IntelliJ\ IDEA\ 14\ CE.app/Contents/MacOS/idea ."
source $dir/kuti
