#!/bin/bash
# source ~/code/myLinux/cmd/bashrc
# dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ## old
dir=`dirname $0`
alias ll="ls -lh"
alias s="subl3 ."
alias sshlab="/home/krister/code/internal-docs/Scripts/ssh_to_router.sh"
source $dir/kuti
ssh-add ~/.ssh/id_rsa &> /dev/null
