#!/bin/bash
alias ll="ls -lah"
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
ssh-add ~/.ssh/id_rsa &> /dev/null
alias deleteAllDocker="/home/krister/code/myLinux/bash/functions.sh deleteAllDocker"
